"""Arcam AV Control"""

# Re-export all public API from submodules for backwards compatibility.
from .dataclasses import (  # noqa: F401
    DEVICE_PROFILES,
    DeviceProfile,
    HdmiSettings,
    NowPlayingInfo,
    PresetDetail,
    RoomEqNames,
    VideoParameters,
    ZoneSettings,
    detect_api_model,
)
from .enums import (  # noqa: F401
    APIVERSION_450_SERIES,
    APIVERSION_860_SERIES,
    APIVERSION_DAB_SERIES,
    APIVERSION_HDA_MULTI_ZONE_SERIES,
    APIVERSION_HDA_PREMIUM_SERIES,
    APIVERSION_HDA_SERIES,
    APIVERSION_PA_SERIES,
    APIVERSION_SA_SERIES,
    APIVERSION_ST_SERIES,
    DEFAULT_SOURCE_MAPPING,
    HDA_SOURCE_MAPPING,
    MUTE_WRITE_SUPPORTED,
    POWER_WRITE_SUPPORTED,
    RC5CODE_DECODE_MODE_2CH,
    RC5CODE_DECODE_MODE_MCH,
    RC5CODE_MUTE,
    RC5CODE_POWER,
    RC5CODE_SOURCE,
    RC5CODE_VOLUME,
    SA_SOURCE_MAPPING,
    SOURCE_CODES,
    SOURCE_WRITE_SUPPORTED,
    ST_SOURCE_MAPPING,
    VOLUME_STEP_SUPPORTED,
    AnswerCodes,
    ApiModel,
    BluetoothStatus,
    CommandCodes,
    DecodeMode2CH,
    DecodeModeMCH,
    DolbyAudioMode,
    EnumFlags,
    IncomingAudioConfig,
    IncomingAudioFormat,
    IncomingVideoAspectRatio,
    IncomingVideoColorspace,
    IntOrTypeEnum,
    MenuCodes,
    NetworkPlaybackStatus,
    NowPlayingEncoder,
    NowPlayingSampleRate,
    PresetType,
    SourceCodes,
)
from .exceptions import (  # noqa: F401
    ArcamException,
    CommandInvalidAtThisTime,
    CommandNotRecognised,
    ConnectionFailed,
    InvalidDataLength,
    InvalidPacket,
    InvalidZoneException,
    NotConnectedException,
    NullPacket,
    ParameterNotRecognised,
    ResponseException,
    UnsupportedZone,
)
from .packets import (  # noqa: F401
    PROTOCOL_ETR,
    PROTOCOL_STR,
    AmxDuetRequest,
    AmxDuetResponse,
    CommandPacket,
    ResponsePacket,
    read_command,
    read_response,
    write_packet,
)

__all__ = [
    # Exceptions
    "ArcamException",
    "ConnectionFailed",
    "NotConnectedException",
    "UnsupportedZone",
    "ResponseException",
    "InvalidZoneException",
    "CommandNotRecognised",
    "ParameterNotRecognised",
    "CommandInvalidAtThisTime",
    "InvalidDataLength",
    "InvalidPacket",
    "NullPacket",
    # API version sets
    "APIVERSION_450_SERIES",
    "APIVERSION_860_SERIES",
    "APIVERSION_DAB_SERIES",
    "APIVERSION_HDA_SERIES",
    "APIVERSION_HDA_PREMIUM_SERIES",
    "APIVERSION_HDA_MULTI_ZONE_SERIES",
    "APIVERSION_SA_SERIES",
    "APIVERSION_PA_SERIES",
    "APIVERSION_ST_SERIES",
    # Enums
    "ApiModel",
    "AnswerCodes",
    "CommandCodes",
    "SourceCodes",
    "MenuCodes",
    "DecodeMode2CH",
    "DecodeModeMCH",
    "IncomingVideoAspectRatio",
    "IncomingVideoColorspace",
    "IncomingAudioFormat",
    "IncomingAudioConfig",
    "NetworkPlaybackStatus",
    "DolbyAudioMode",
    "NowPlayingSampleRate",
    "NowPlayingEncoder",
    "BluetoothStatus",
    "PresetType",
    # Data classes
    "PresetDetail",
    "VideoParameters",
    "NowPlayingInfo",
    "HdmiSettings",
    "ZoneSettings",
    "RoomEqNames",
    "ResponsePacket",
    "CommandPacket",
    "AmxDuetRequest",
    "AmxDuetResponse",
    # RC5 code mappings
    "RC5CODE_SOURCE",
    "RC5CODE_POWER",
    "RC5CODE_MUTE",
    "RC5CODE_VOLUME",
    "RC5CODE_DECODE_MODE_2CH",
    "RC5CODE_DECODE_MODE_MCH",
    # Feature support sets
    "POWER_WRITE_SUPPORTED",
    "MUTE_WRITE_SUPPORTED",
    "SOURCE_WRITE_SUPPORTED",
    "VOLUME_STEP_SUPPORTED",
    # Device profiles
    "DeviceProfile",
    "DEVICE_PROFILES",
    "detect_api_model",
    # Source mappings
    "SOURCE_CODES",
    "DEFAULT_SOURCE_MAPPING",
    "HDA_SOURCE_MAPPING",
    "SA_SOURCE_MAPPING",
    "ST_SOURCE_MAPPING",
    # Protocol I/O
    "read_response",
    "read_command",
    "write_packet",
]
